// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wfkwhjsrxfjscwkohtmf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indma3doanNyeGZqc2N3a29odG1mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxMDUwNzQsImV4cCI6MjA3MDY4MTA3NH0.PoBouOI0cdbAjGdgImAwWeeVzsf3VP2FvAwtQIqYT2I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});